# Generated by Django 5.0.1 on 2024-02-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brinquedos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='preco_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
